export default {
  OVERLAY: "#twik-generic-cart-overlay",
  SIDEBAR_CART_WRAPPER: "#twik-sidebar-cart-wrapper",
  SIDEBAR_CART: "#twik-sidebar-cart",
  CART_PRODUCT_LIST: ".twik-cart-product-list",
  CART_EMPTY: ".twik-cart-empty",
  ORIGINAL_CART_BUTTON: `a[href="/cart"]`,
  APPLIED_MESSAGE_COUPON: ".twik-applied-coupon-message",
  APPLIED_MESSAGE_COUPON_SUCCESS: ".twik-applied-coupon-message .success",
  APPLIED_MESSAGE_COUPON_ERROR: ".twik-applied-coupon-message .error",
  APPLIED_MESSAGE_COUPON_NOCOUPON: ".twik-applied-coupon-message .nocoupon",
  APPLIED_COUPON: ".twik-applied-coupon",
  COUPON_NAME: ".twik-coupon-name",
  APPLIED_COUPON_WRAPPER: ".twik-applied-coupon-container",
  COUPON_LOADING: ".coupon-loading",
  CART_SUBTOTAL: ".twik-cart-subtotal",
  CART_PRODUCT_QUANTITY_INPUT: ".twik-cart-product-quantity-input",
  CART_PRODUCT_QUANTITY_SPAN: ".twik-cart-product-quantity-span",
  PLUS_ONE: ".twik-plus-one",
  MINUS_ONE: ".twik-minus-one",
  REMOVE_ITEM: ".twik-remove-item",
  CART_CLOSE_WRAPPER: ".twik-cart-close-wrapper",
  APPLY_COUPON_FORM: ".twik-apply-coupon-form",
  APPLY_COUPON_INPUT: ".twik-apply-coupon-input",
  REMOVE_COUPON: ".remove-applied-coupon",
  COUPON_AMOUNT: ".twik-coupon-amount",
};
